---
title: Demystifying Machine Intelligence
date: 2016-01-15 16:07:07 Z
tags:
- interview
- artificial intelligence
- data science
- language generation
layout: post
tumblr_url: http://blog.fastforwardlabs.com/post/137351428898/demystifying-machine-intelligence
---

<p>We recently co-hosted an event at <a href="http://www.1871.com">1871 </a>in Chicago with Kris Hammond, Chief Scientist at Narrative Science. Called “Technology Explained,” the event helped attendees understand why machine intelligence is succeeding today and how businesses can leverage new technologies to make better decisions and optimize efficiency. Some highlights: </p><p><b>Fast Forward Labs’ Mission: Help Companies Understand New Data Technologies</b></p><p>Kris Hammond described Fast Forward Labs as a “different kind of consulting company, aimed at giving companies the ability to look at things in the world that they might not understand and provide them with that understanding.” As Hilary explained in a recent <a href="http://www.techrepublic.com/article/hilary-mason-fast-forward-labs-ceo-one-time-aspiring-taxi-driver-your-nerd-best-friend/">TechRepublic interview</a>, our goal is to help companies build new products using technologies that are more possible this year than last year. <br/></p><p><br/></p><figure class="tmblr-embed tmblr-full" data-provider="youtube" data-orig-width="540" data-orig-height="304" data-url="https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dt2P938eJC5o"><iframe width="540" height="304" id="youtube_iframe" src="https://www.youtube.com/embed/t2P938eJC5o?feature=oembed&amp;enablejsapi=1&amp;origin=https://safe.txmblr.com&amp;wmode=opaque" frameborder="0"></iframe></figure><p><b><br/></b></p><p><b>The Promise Natural Language Generation: Demystifying Data</b><br/></p><p>Kris Hammond used an example from the lakefront of the City of Chicago to demonstrate the promise of natural language generation as a tool that “transforms the world of pure, impenetrable data into something that any parent can read and make a decision about.” </p><p><br/></p><figure class="tmblr-embed tmblr-full" data-provider="youtube" data-orig-width="540" data-orig-height="304" data-url="https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D1ynX0qZ8p9k%26feature%3Dyoutu.be"><iframe width="540" height="304" src="https://www.youtube.com/embed/1ynX0qZ8p9k?feature=oembed&amp;enablejsapi=1&amp;origin=https://safe.txmblr.com&amp;wmode=opaque" frameborder="0"></iframe></figure><p><b><br/></b></p><p><b>What’s Next for Fast Forward: Text Summarization</b></p><p>Hilary gave a sneak peak of our upcoming text summarization report. We’re combining language generation and neural methods to extract the key sentences for larger documents, and, in the near future, present different points of view from a document corpus. </p><p><br/></p><figure class="tmblr-embed tmblr-full" data-provider="youtube" data-orig-width="540" data-orig-height="304" data-url="https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3Dn9dqy22ow40%26feature%3Dyoutu.be"><iframe width="540" height="304" src="https://www.youtube.com/embed/n9dqy22ow40?feature=oembed&amp;enablejsapi=1&amp;origin=https://safe.txmblr.com&amp;wmode=opaque" frameborder="0"></iframe></figure>
